# Generated by Django 5.0.2 on 2024-05-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='hire_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
